Models/ErrorViewModel.cs
namespace JobPortalWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/JobApplicant.cs
namespace JobPortalWeb.Models
{
    public class JobApplicant
    {
        public string name { get; set; }
        public string collegeName { get; set; }
        public int Jobid { get; set; }
        public int phoneNo { get; set; }
        public string emialid { get; set; }
    }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.Configuration;
using static JobPortalWeb.Controllers.JobListController;

namespace JobPortalWeb.Controllers
{

   
    public class AdminController : Controller
    {

        IConfiguration _configuration;
        public AdminController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {

            string conString = _configuration.GetConnectionString("AllJobDB");
            //Console.WriteLine("Envvar" + _configuration["mykey"]);
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = conString;
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT * FROM JobList";
            SqlDataReader reader = cmd.ExecuteReader();

            List<AllJob> allJobList = new();
            while (reader.Read())
            {
                AllJob alljob = new AllJob();
                alljob.Id = (int)reader["JobID"];
                alljob.Name = (string)reader["JobName"];
                alljob.Domain = (string)reader["JobDomain"];
                alljob.DateOfReg = (DateTime)reader["LastDateForRegistration"];


                allJobList.Add(alljob);
            }
            ViewBag.allJobList = allJobList;
            conn.Close();
            return View();
        }

        public IActionResult ViewAllApplicant()
        {

            var jID = Request.Query["id"];
            ViewBag.JobID = jID;

            string conString = _configuration.GetConnectionString("AllJobDB");
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = conString;
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = $"SELECT * FROM Applicants WHERE Jobid = {jID}";
            SqlDataReader reader = cmd.ExecuteReader();

            List<ApplicantsDetails> allApplicant = new();
            while (reader.Read())
            {
                ApplicantsDetails ad = new ApplicantsDetails();
                ad.Id = (int)reader["ApplicantID"];
                ad.Name = (string)reader["name"];
                ad.PhoneNo = (int)reader["phoneNo"];
                //ad.email = (string)reader["email"];
                ad.CollegeName = (string)reader["collegeName"];

                allApplicant.Add(ad);

                //Console.WriteLine(reader["emailid"]);

            }
            
            ViewBag.allApplicants = allApplicant;
            conn.Close();

            return View();
        }

        public class ApplicantsDetails
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string CollegeName { get; set; }
            public int PhoneNo { get; set; }
            public string email = "EMAIl ID";
                
        }
    }
}

Controllers/HomeController.cs
using JobPortalWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace JobPortalWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/JobListController.cs
using JobPortalWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;
using System.Configuration;

namespace JobPortalWeb.Controllers
{
    public class JobListController : Controller
    {
        IConfiguration _configuration;
        public JobListController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult JobList()
        {
            string conString = _configuration.GetConnectionString("AllJobDB");
            //Console.WriteLine("Envvar" + _configuration["mykey"]);
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = conString;
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT * FROM JobList";
            SqlDataReader reader = cmd.ExecuteReader();

            List<AllJob> allJobList = new();
            while (reader.Read())
            {
                AllJob alljob = new AllJob();
                alljob.Id = (int)reader["JobID"];
                alljob.Name = (string)reader["JobName"];
                alljob.Domain = (string)reader["JobDomain"];
                alljob.DateOfReg = (DateTime)reader["LastDateForRegistration"];


                allJobList.Add(alljob);
            }
            ViewBag.allJobList = allJobList;
            conn.Close();
            return View();
        }

        public class AllJob
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Domain { get; set; }

            public DateTime DateOfReg { get; set; }


        }



        public IActionResult JobApply()
        {

            var jID = Request.Query["id"];

            ViewBag.JobID = jID;



            string conString = _configuration.GetConnectionString("AllJobDB");
            //Console.WriteLine("Envvar" + _configuration["mykey"]);
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = conString;
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandText = $"SELECT * FROM JobList WHERE JobId = 1";

            //Console.WriteLine(jID);

            SqlDataReader reader = cmd.ExecuteReader();

            
          
            AllJob jobDetails = new AllJob();
            while (reader.Read())
            {
                jobDetails.Id = (int)reader["JobID"];
                jobDetails.Name = (string)reader["JobName"];
                jobDetails.Domain = (string)reader["JobDomain"];
                jobDetails.DateOfReg = (DateTime)reader["LastDateForRegistration"];

            }
     

            ViewBag.JobDetails = jobDetails;
            conn.Close();


            return View();



        }


        [HttpPost]
        public ActionResult JobApply(JobApplicant applicant)
        {
            var jID = Request.Query["id"];
            ViewBag.JobID = jID;

            int jobID = applicant.Jobid;
            string name = applicant.name;
            string emailID = applicant.emialid;
            int phoneNo = applicant.phoneNo;
            string collegeName = applicant.collegeName;


            Console.WriteLine("INTO HTTPPOST");
            //Writing to DB

            string conString = _configuration.GetConnectionString("AllJobDB");
            //Console.WriteLine("Envvar" + _configuration["mykey"]);
            SqlConnection conn = new SqlConnection();
            conn.ConnectionString = conString;
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
  
            cmd.CommandText = $"INSERT INTO Applicants values ('{name}','{collegeName}','{emailID}',{phoneNo},{jID})";

            Console.WriteLine($"INSERT INTO Applicants values ('{name}','{collegeName}','{emailID}',{phoneNo},{jID})");
            try
            {
                int re = cmd.ExecuteNonQuery();
                Console.WriteLine("DATA UPDATED!");

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message ); 
            }

            return View();
        }

        
    }
}

Views/Admin/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<h6>List of All Jobs Admin Controller</h6>
<table class='table'>
    <thead>
        <tr>
            <th>Job ID</th>
            <th>Job Name</th>
            <th>Domain</th>
            <th>late Date for Registration</th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var j in ViewBag.allJobList)
            {
                <tr>
                    <td>@j.Id</td>
                    <td>@j.Name</td>
                    <td>@j.Domain</td>
                    <td>@j.DateOfReg</td>
                    <td>
                        <a class="btn-primary" href="Admin/ViewAllApplicant?id=@j.Id"> View Applicant</a>
                    </td>
                    <td>
                        <a class="btn-primary" href="/JobList/JobApply?id=@j.Id"> Edit Job</a>
                    </td>

                </tr>
            }
        }
    </tbody>
</table>

Views/Admin/ViewAllApplicant.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h6>All Applicants</h6>
<p1>Job ID : @ViewBag.JobID</p1>

<table class='table'>
    <thead>
        <tr>
            <th>Applicant ID</th>
            <th> Name</th>
            <th>College Name</th>
            <th>Phone Np</th>
            <th>Email ID</th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var j in ViewBag.allApplicants)
            {
                <tr>
                    <td>@j.Id</td>
                    <td>@j.Name</td>
                    <td>@j.CollegeName</td>
                    <td>@j.PhoneNo</td>
                    <td>@j.email</td>
                </tr>
            }
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/JobList/JobApply.cshtml
@model JobPortalWeb.Models.JobApplicant

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Aply Job</title>
</head>
<body>
    <h1> Apply for Job ID : @ViewBag.JobID</h1>
    @using (Html.BeginForm(FormMethod.Post))
    {
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th colspan="2" align="center">Person Details</th>
            </tr>

            <tr>
                <td>Name: </td>
                <td>
                    @Html.TextBoxFor(m => m.name)
                </td>
            </tr>

            <tr>
                <td>Collge Name: </td>
                <td>
                    @Html.TextBoxFor(m => m.collegeName)
                </td>
            </tr>
            
            <tr>
                <td>Phone No: </td>
                <td>
                    @Html.TextBoxFor(m => m.phoneNo)
                </td>
            </tr>
            <tr>
                <td>Email ID: </td>
                <td>
                    @Html.TextBoxFor(m => m.emialid)
                </td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Submit" /></td>
            </tr>
        </table>
    }
</body>
</html>

Views/JobList/JobList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>List of All Jobs</h1>
<table class='table'>
    <thead>
        <tr>
            <th>Job ID</th>
            <th>Job Name</th>
            <th>Domain</th>
            <th>late Date for Registration</th>
        </tr>
    </thead>

    <tbody>
        @{
            foreach (var j in ViewBag.allJobList)
            {
                <tr>
                    <td>@j.Id</td>
                    <td>@j.Name</td>
                    <td>@j.Domain</td>
                    <td>@j.DateOfReg</td>
                    <td>
                        <a class="btn-primary" href="/JobList/JobApply?id=@j.Id"> Apply</a>
                    </td>

                </tr>
            }
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobPortalWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobPortalWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobPortalWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="JobList" asp-action="JobList">AllJobs</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - JobPortalWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>